<?php

use Illuminate\Database\Seeder;

class TesdaStudinfoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $courses = DB::table('tesda_courses')->select('id')->get();
        DB::table('tesda_studinfo')->truncate();
        DB::table('tesda_studinfo')->insertOrIgnore([
            [
                'sid' => '2025001',
                'userid' => 1,
                'lrn' => 'LRN000001',
                'lastname' => 'Dela Cruz',
                'firstname' => 'Juan',
                'middlename' => 'Santos',
                'suffix' => null,
                'dob' => '2000-01-01',
                'gender' => 'Male',
                'contactno' => '09171234567',
                'mothername' => 'Maria Dela Cruz',
                'mcontactno' => '09181234567',
                'moccupation' => 'Housewife',
                'fathername' => 'Jose Dela Cruz',
                'fcontactno' => '09192234567',
                'foccupation' => 'Farmer',
                'guardianname' => 'N/A',
                'gcontactno' => 'N/A',
                'levelid' => 1,
                'deleted' => 0,
                'courseid' => $courses->random()->id,
                'createddatetime' => now(),
                'updateddatetime' => now(),
            ],
            [
                'sid' => '2025002',
                'userid' => 2,
                'lrn' => 'LRN000002',
                'lastname' => 'Santos',
                'firstname' => 'Maria',
                'middlename' => 'Reyes',
                'suffix' => null,
                'dob' => '1999-05-15',
                'gender' => 'Female',
                'contactno' => '09171234568',
                'mothername' => 'Carmen Santos',
                'mcontactno' => '09181234568',
                'moccupation' => 'Teacher',
                'fathername' => 'Manuel Santos',
                'fcontactno' => '09192234568',
                'foccupation' => 'Engineer',
                'guardianname' => 'N/A',
                'gcontactno' => 'N/A',
                'levelid' => 2,
                'deleted' => 0,
                'courseid' => $courses->random()->id,
                'createddatetime' => now(),
                'updateddatetime' => now(),
            ],
            [
                'sid' => '2025003',
                'userid' => 3,
                'lrn' => 'LRN000003',
                'lastname' => 'Garcia',
                'firstname' => 'Pedro',
                'middlename' => 'Lopez',
                'suffix' => null,
                'dob' => '2001-03-10',
                'gender' => 'Male',
                'contactno' => '09171234569',
                'mothername' => 'Josefina Garcia',
                'mcontactno' => '09181234569',
                'moccupation' => 'Vendor',
                'fathername' => 'Pablo Garcia',
                'fcontactno' => '09192234569',
                'foccupation' => 'Carpenter',
                'guardianname' => 'N/A',
                'gcontactno' => 'N/A',
                'levelid' => 3,
                'deleted' => 0,
                'courseid' => $courses->random()->id,
                'createddatetime' => now(),
                'updateddatetime' => now(),
            ],
            [
                'sid' => '2025004',
                'userid' => 4,
                'lrn' => 'LRN000004',
                'lastname' => 'Reyes',
                'firstname' => 'Ana',
                'middlename' => 'Cruz',
                'suffix' => null,
                'dob' => '2002-07-20',
                'gender' => 'Female',
                'contactno' => '09171234570',
                'mothername' => 'Luisa Reyes',
                'mcontactno' => '09181234570',
                'moccupation' => 'Seamstress',
                'fathername' => 'Ramon Reyes',
                'fcontactno' => '09192234570',
                'foccupation' => 'Driver',
                'guardianname' => 'N/A',
                'gcontactno' => 'N/A',
                'levelid' => 4,
                'deleted' => 0,
                'courseid' => $courses->random()->id,
                'createddatetime' => now(),
                'updateddatetime' => now(),
            ],
            [
                'sid' => '2025005',
                'userid' => 5,
                'lrn' => 'LRN000005',
                'lastname' => 'Martinez',
                'firstname' => 'Carlos',
                'middlename' => 'Diaz',
                'suffix' => null,
                'dob' => '1998-11-25',
                'gender' => 'Male',
                'contactno' => '09171234571',
                'mothername' => 'Margarita Martinez',
                'mcontactno' => '09181234571',
                'moccupation' => 'Nurse',
                'fathername' => 'Victor Martinez',
                'fcontactno' => '09192234571',
                'foccupation' => 'Mechanic',
                'guardianname' => 'N/A',
                'gcontactno' => 'N/A',
                'levelid' => 5,
                'deleted' => 0,
                'courseid' => $courses->random()->id,
                'createddatetime' => now(),
                'updateddatetime' => now(),
            ],
        ]);
    }
}
